### ISSUE TITLE
[MRIQC] Tag inheritance issue in MRIQC for BOLD

### ISSUE THREAD

**Issue by servoz** [populse/mia_processes#13]
We observe the usual pop-up when there are several files in input and Mia does not know which tags to use for inheritance for the output files.

![Screenshot from 2022-10-28 16-56-37](https://user-images.githubusercontent.com/37933899/198667045-22463b6b-5df9-4fe1-a4c1-06aa16430384.png)

Normally, this should be handled before going through the MRIQC_func_report brick.
It seems that there are indeed issues with tag inheritance if we see the database in the data browser.

To investigate deeper.

**Comment by servoz** [comment]
I've just had a look.

I have not looked at everything, but we can see that (at least) [for the TSNR brick, the retrieval of input data from the database does not work (we just retrieve None)](https://github.com/populse/populse_mia/blob/master/python/populse_mia/user_interface/pipeline_manager/pipeline_manager_tab.py#L648). Without having had the time to look in detail why, this does not come from the brick itself since the inheritance works perfectly if we launch the calculation only on the TSNR brick. Are we dealing with a database query on a not yet indexed data? In V1 of populse_mia we coded so that the initialisation was done exactly in the order of the bricks calculation. In V2 this part of the code has gone and I never got time to reading in detail how it was done now. There are also some tag inheritance issues in the Anat MRIQC pipeline (but much less) which could also be due to the same reason ....

For the moment, because I really don't have the time to look into this issue which will certainly be time-consuming to fix in a clean way, I have just done quick and dirty by adding in the brick a forced inheritance from functional data input (which is necessarily indexed in the database!).

So we don't see the pop-up anymore but the original problem is still not really fixed (and the question raised (order of the bricks in initialisation) is certainly a substantive one!!!)

**Comment by manuegrx** [comment]
When I use the mriqc pipeline for one subject, I don't have this inheritance problem, but when I use the mriq pipeline for several subjects  (using "Iterate pipeline"), I have several inheritance problems for both the functional pipeline and the anat pipeline. 

![inheritance_mriqc_iteration](https://user-images.githubusercontent.com/47973414/234819268-fc084e51-37fa-4362-9eab-884c6b0965dd.png)

**Comment by servoz** [comment]
I don't really see why the iteration mode changes things in inheritance, compared to the unit mode...
We should do some introspection ...
It would be better to fix the main issue in a clean and permanent way anyway ...
For the moment, due to lack of time, we are applying many patches in a quick and dirty way ...
If we continue like this, Mia will look like Windows :-((((
I already have a lot of tickets to manage at the moment. I'll look into it ASAP.

**Comment by servoz** [comment]
I started looking at this old ticket.

A lot has been improved recently regarding tag inheritance. It may be that the issues have already been fixed?

I've just tested MRIQC iteration with 3 subjects and I don't see any problem (first method, [via a regular iterative pipeline](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)). Since there are three ways to iterate, I'd like to be sure it's really fixed for all cases.
@manuegrx can you do a test on your side, please ?
and if the if the issue you described persists, please give a minimal procedure to reproduce so that I can examine it in more detail?

**Comment by manuegrx** [comment]
I tested using the second method (via [Input_Filter brick/process without use of the iteration table](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#without-use-of-the-iteration-table)) for both pipeline and I no longer have any inheritance problems (I was using this method also in my last comment). 
So I think you have right and the last improvements fixed the issue :)

**Comment by servoz** [comment]
Thanks !
