### ISSUE TITLE
[bricks in progress] mia_processes.bricks.preprocess.spm.Realign

### ISSUE THREAD

**Issue by servoz** [populse/mia_processes#28]
[We need to manage the completion of the outputs at the time of initialisation, even if the inputs do not yet exist.](https://github.com/populse/populse_mia/issues/298)

**Comment by servoz** [comment]
It seems that the issue is now fixed. Please @manuegrx, do the necessary tests and feel free to reopen this ticket if necessary!

**Comment by manuegrx** [comment]
The fix is working, thank you
