### ISSUE TITLE
built docs are in git sources

### ISSUE THREAD

**Issue by denisri** [populse/mia_processes#4]
The HTML docs of mia_processes have been added in git sources. Is it intentional ? As they are not source files I would expect them to be built during the install process and not included in the sources ?
Moreover it is possible to setup travis-ci (or maybe git actions) to build them automatically when some changes are pushed into the master branch and to push them into https://populse.github.io/mia_processes automatically, as is already done for capsul or soma-workflow. The "problem" there is that to build the docs we need to install capsul and populse_mia, which is very big (my git repo for populse_mia is 2.4Go large !), thus doing it at each push would be somewhat expensive for now.

**Comment by servoz** [comment]
Indeed, the best would be that they are automatically generated each time we push in Github ! It would avoid to do by hand (and forget to do) the "html make" each time ... Let's talk about it at our next meeting on March 16th ?

**Comment by denisri** [comment]
OK.

**Comment by denisri** [comment]
I could setup an automatic build of the doc on travis-ci with minimal installation of dependent projects (populse_mia, capsul, soma-base). I could avoid downloading the full 2.4 Go of populse_mia data using the github svn interface (apparently it is not possible to download part of a project using git). So I will remove the built docs from the sources on master branch, and push it.

**Comment by servoz** [comment]
All right. I'm just starting to play with the possibility you suggest to create html files automatically from the docstrings (I wish I could create the exact same display as when I created html from .rst files by hand!). This is more related to #3. We'll keep in touch ...

**Comment by denisri** [comment]
Yes I am setting up the build on master, and then will merge in the other branch so that #3 will follow the same mechanism.

**Comment by servoz** [comment]
There seems to be a problem with deployment ?

**Comment by denisri** [comment]
The gh-pages branch seems to have been built, and contains HTML pages and an index.html, but the URL https://populse.github.io/mia_processes/ seems to redirect to https://populse.github.io/mia_processes/html/index.html (with an "html" subdirectory), which I don't understand.
Saying that I realize that docs had already been pushed (manually I guess) on https://populse.github.io/mia_processes/html/index.html but no gh-pages branch did exist, so I don't know how they have been pushed there.

**Comment by servoz** [comment]
Ok I seen your fix for docs in place of doc and we have now "just" to understand the redirection problem ... I will try also to see what is wrong !

**Comment by denisri** [comment]
Yes that's it...
Do you remember how the older pages were pushed ? Maybe there was a trick there that we have to disable ?

**Comment by servoz** [comment]
wait a minute i think a see ..

**Comment by servoz** [comment]
ok in the settings. the GitHub Pages site was  built from master branch docs folder, not the gh-pages branch !!! Sorry by that, it is now corrected !

**Comment by servoz** [comment]
It's true that one goes fast, but two go further. Thank you @denisri for this improvement in the automatic doc management. I'm continuing my odds to try and get the rendering I like from the docstrings (#3). We stay in touch
