### ISSUE TITLE
[general]  self.output_directory initialisation issue 

### ISSUE THREAD

**Issue by manuegrx** [populse/mia_processes#40]
As explain in https://github.com/populse/mia_processes/issues/22 we need to add a sub-folder in `derived_data` for each subject for some brick (as in EstimateModel). 

The idea was to redefine self.output_directory path in each brick. 
For example in the EstmiateModel brick : 
 ```
           if self.output_directory:
                # Change output_directory for this process in order to
                # use a specific directory for each analysis

                if os.path.dirname(
                    spm_mat_dir
                ) == self.output_directory and "data" in os.path.basename(
                    spm_mat_dir
                ):
                    # if spm_mat already in a subfolder for a analysis
                    out_directory = spm_mat_dir
                else:
                    # if spm_mat file not in a subfolder(for e.g spm_mat
                    # file in download data)
                    sub_name = get_dbFieldValue(
                        self.project, self.spm_mat_file, "PatientName"
                    )
                    if sub_name is None:
                        print(
                            "Please, fill 'PatientName' tag "
                            "in the database for SPM file"
                        )
                        return self.make_initResult()

                    out_directory = os.path.join(
                        self.output_directory, sub_name + "_data"
                    )

                    if not os.path.exists(out_directory):
                        os.mkdir(out_directory)
                self.output_directory = out_directory
            else:
                print("No output_directory was found...!\n")
                return self.make_initResult()

```

It is working correctly when using the brick alone or in a pipeline. 

However, if we are using iteration there is an issue : 
- at the begging of the brick for the second subject : self.output_directory = ".../data/derived_data/sub-01" and not  self.output_directory = ".../data/derived_data/"
- the outputs are therefore created in   ".../data/derived_data/sub-01/sub-02"

**Comment by manuegrx** [comment]
To quickly reproduce the issue, for example, in a new project: 
- add two time the test subject alej, one time with the name 001 and one time with the name 002
- add (using the "add document" button) the regressor physio (regressor_physio_EtC02_ctl.mat)
- for each subject (001 and 002) run level1design brick  (only filled the sess_scans parameter with the scan and the sess_mtlti_reg parameter with the regressor)
- For the estimateModel brick, click on  "Iterate pipeline" and choose to iterate over spm_mat_file. Select both SPM.mat file created before and run the brick

(It will be better to test also the iteration with a pipeline with level1design, estimateModel and EstimateContrast brick but there is currently an issue to iterate Level1design brick)

**Comment by manuegrx** [comment]
The issue also appears when you stay on the same pipeline/ brick to do a second subject

To reproduce: 
- add two time the test subject alej, one time with the name 001 and one time with the name 002
- add (using the "add document" button) the regressor physio (regressor_physio_EtC02_ctl.mat)
- for each subject (001 and 002) run level1design brick (only filled the sess_scans parameter with the scan and the sess_mtlti_reg parameter with the regressor)
- Run EstimateModel for subject 001
- Stay on the same pipeline and change the smp_mat_file  for subject 002. Run the brick

**Comment by servoz** [comment]
> To reproduce:

>    add two time the test subject alej, one time with the name 001 and one time with the name 002
>   add (using the "add document" button) the regressor physio (regressor_physio_EtC02_ctl.mat)
>    for each subject (001 and 002) run level1design brick (only filled the sess_scans parameter with the scan and the sess_mtlti_reg parameter with the regressor)
>    Run EstimateModel for subject 001
>    Stay on the same pipeline and change the smp_mat_file for subject 002. Run the brick

OK I reproduce ... I start to look for a fix ..

**Comment by servoz** [comment]
I made a fix for the last `To reproduce case`.

@manuegrx, can you please try on your side with different cases.

I also need to do some tests on my end.

**Comment by manuegrx** [comment]
It works on my side for both issues (it is okay when I stay on the same pipeline/ brick to do a second subject and it is okay when I iterated ) :) 

Thanks !

**Comment by servoz** [comment]
Thank you.
As it's good for you, I'm going to close this ticket after a final survey.
I think we can do better. I need some time for a final fix and testing with bricks that are not an instance of ProcessMIA.
