### ISSUE TITLE
CVR pipeline issue with iteration 

### ISSUE THREAD

**Issue by manuegrx** [populse/mia_processes#85]
I would like to iterate on several subjects the [CVR pipeline](https://populse.github.io/mia_processes/html/documentation/pipelines/CerebVascularReact/CO2_inhalation.html) and I have some issues. 

My first attempt was to test the [via input filter brick process way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process)  
![itretae2](https://github.com/user-attachments/assets/0318592c-1de8-4eae-b3be-0113a1546023)

But an issue arises: 
 ```  
raise TraitError(
traits.trait_errors.TraitError: The 'func_file' trait of a Make_CVR_reg_physio instance must be a pathlike object or string representing a file or a _Undefined or None, but a value of [<undefined>] <class 'traits.trait_list_object.TraitListObject'> was specified.
``` 

The `func_files` parameter is link to the `func_file` parameter of the [Make_CVR_reg_phyiso](https://populse.github.io/mia_processes/html/documentation/bricks/tools/Make_CVR_reg_physio.html) brick  and to  the `func_files` parameter of the [Bold_spatial_preprocessing1](https://populse.github.io/mia_processes/html/documentation/pipelines/preprocess/Bold_spatial_preprocessing1.html)  brick.  
In the first case, the type is the following: 
 ```
  self.add_trait(
            "func_file",
            Either(
                ImageFileSPM(),
                Undefined,
                copyfile=False,
                output=False,
                optional=False,
                desc=func_file_desc,
            ),
        )
 ``` 

and for the Bold_spatial_preprocessing1 the type is : 
```
self.add_trait(
            "in_files",
            InputMultiPath(
                Either(ImageFileSPM(), List(ImageFileSPM()), Undefined),
                copyfile=True,
                output=False,
                optional=False,
                desc=in_files_desc,
            ),
        )
```

I suppose that the problem is that in one case it could be a list and in the other not.  
How could I manage this issue ? I am not sure if the best way is to look how to modify the pipeline or to look how to change the way the iteration is done

**Comment by manuegrx** [comment]
I also test an other way to do the iteration, using [a regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table) using the  `Files_To_List` brick and it is not working either.  
![iterate_files_to_list](https://github.com/user-attachments/assets/c8a335c5-077a-45b5-bf04-0b3f6b2b875f)

We can create the iterative pipeline and launch it but  it fails with same issue: 
```
error in setting parameters of process Make_CVR_reg_physio, with dict: {'func_file': ['/home/gourieuxe/Documents/MIA_projects/projetVaso_CVR_assemblynet_2/data/raw_data/sub-002-ses-01--0-func-sub-002_ses-01_task-cvr240dyn_run-12_bold-.nii'], 'cvr_reg': '/home/gourieuxe/Documents/MIA_projects/projetVaso_CVR_assemblynet_2/data/derived_data/sub-002_data/CVR_physio_reg.mat', 'output_directory': '/home/gourieuxe/Documents/MIA_projects/projetVaso_CVR_assemblynet_2/data/derived_data'}

[....]
    raise TraitError(

traits.trait_errors.TraitError: The 'func_file' trait of a Make_CVR_reg_physio instance must be a pathlike object or string representing a file or a _Undefined or None, but a value of ['/home/gourieuxe/Documents/MIA_projects/projetVaso_CVR_assemblynet_2/data/raw_data/sub-002-ses-01--0-func-sub-002_ses-01_task-cvr240dyn_run-12_bold-.nii'] <class 'list'> was specified.
```

I also try to not use Files_to_List for `func_files` but in this case we cannot select the functional data with "Filter"
![iterate](https://github.com/user-attachments/assets/7787c125-9e9a-4396-8ac5-f95fb2805dc6)

![iterate2](https://github.com/user-attachments/assets/620fe936-521d-4444-9811-54f1d003f813)

**Comment by servoz** [comment]
very interesting!

**Comment by manuegrx** [comment]
I believe I've figured out a way to work around the issue but it is not a "deep correction" (it is not at the level of populse or capsul but in each pipelinel) so I do not know if it is the ideal solution. 

My idea is to add in the main pipeline (here CVR pipeline) a  brick when an input is used for several bricks and that the brick inputs are not the same type. 

For example, for the CVR pipeline I create a brick (`InputMultiPath_to_File`) to "convert" the type `InputMultiPath(Either(ImageFileSPM(), List(ImageFileSPM()), Undefined)` to a file `ImageFileSPM(output=True, desc=file_desc)`. 

This brick can be added to the main pipeline before the brick Make_Cvr_Reg_Physio and then the type of the main input "func_files" is `InputMultiPath(Either(ImageFileSPM(), List(ImageFileSPM()), Undefined) ` for both `1_spatial_preprocessing` and `InputMultiPath_to_File` bricks : 

![CVR_add_inputMultipath_to_file](https://github.com/user-attachments/assets/6e8e739d-51f1-4386-b89e-d8c4ec74f036)


Then we can iterate the CVR pipeline as explain is the doc using [a regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table) using the Files_To_List brick and it is working this time (it is also working with the brick ReduceNode from capsul): 
![CVR_pipeline_to_iterate](https://github.com/user-attachments/assets/3690a73b-38d2-450e-9f3f-67305bef322c)

However, the pipeline can not be correctly initialized using the [ input filter brick process way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) to iterate. 
There is no more error (as before) but the pipeline is not initialized correctly and for now I do not understand why... 



(The proposed solution is in the branch https://github.com/populse/mia_processes/tree/85-cvr-pipeline-issue-with-iteration )

**Comment by servoz** [comment]
great!

However, I think this patch could also work with the existing `List_To_File` brick.
While we wait for a real fix, I think it might do the job (the user just needs to modify the existing pipeline with the `List_To_File` brick, then save the new pipeline to their personal library).

I'm very busy at the moment and doubt I'll have time to look at this in detail now.

**Comment by manuegrx** [comment]
Indeed it is also working with the existing List_To_File brick if you used the pipeline only for iteration but not if you want to use it for only one subject. 

With the `InputMultiPath_to_File` brick it works for iteration and for one subject, so it could be added to the main CVR pipeline in the main branch  while we wait for a potential real fix. If it is okay for you I can do it (I can maybe change the name of the brick ...)

**Comment by servoz** [comment]
I think that if the user wants to do the calculation on a single subject, it's enough to use the pipeline without changing anything.

**Comment by manuegrx** [comment]
Okay ! I'm leaving this issue open to not forgot to fix the real issue. 

To summarize, for now, if you want to use iteration with the CVR pipeline, follow theses steps: 

- Open the C02_inalation pipeline and click to Edit sub-pipeline 

- Add the brick `List_To_File` and save the new pipeline in your personal library 
![Screenshot from 2024-09-05 15-05-31](https://github.com/user-attachments/assets/06769cc3-df18-46ea-980a-3452c99faf45)

- Iterate this new CVR pipeline as explain is the doc using [a regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table) using the `Files_To_List` brick.

**Comment by servoz** [comment]
Great!

I think it's best to avoid putting patches in the master. We (I?) need to take a serious look at the issue you've pointed out and fix it properly and permanently (for all 3 iteration modes).

This pipeline has not been tested in `iteration mode`. There was already a lot of work to be done to make it work properly on a single subject with reproducible results compared with what was obtained with the Amigo software.

I think we're going to discover other problems in iteration mode (the opposite would be really surprising!)...
The first that springs to mind is certainly the patient reference in the report, which could be the one used for the first subject (to be checked, but it's quite possible!).

So I think this ticket could be used to list all the issues in `iteration mode` for the `CVR pipeline`, and why not fix them!

**Comment by manuegrx** [comment]
I spotted at least one other issue with the subject information. 

In my case, I don't want to fill the `patient_info` parameter for each subject, I want to used  the information already in the database (as planned in the code). 

It is correctly working for the first subject of the iteration but not for the next ones. It is because the parameter `self.patient_info` in the `class ReportCO2inhalCvr` is not reset after the first subject. So for example at [line 1395](https://github.com/populse/mia_processes/blob/master/mia_processes/bricks/reports/reporting.py#L1395) the value of `self.patient_info["PatientRef"]` is not `None` or `Undefined` but it is already the value of the first subject and so it is not updated for the second subject. 

For now, I don't have any leads

**Comment by servoz** [comment]
So the first 2 issues we see with iterating the CVR pipeline are :
-1`TraitError` with the `func_file` of the `Make_CVR_reg_physio` instance (must be a pathlike object and we observe an object of type list).
-2 The patient reference in the reports remains the same as that used for the first subject in all reports.

**Comment by servoz** [comment]
I've made a few modifications (`populse_mia` branch `AddIterationInfoInMiaProcess` and `mia_processes` branch `issue#85`) to fix the -1 and -2 issues observed.

In a nutshell,  the processes in the mia_processes library have access to their plugged state of in the pipeline, but now also have access to information about the iterative nature of the pipeline. In addition, the CVR pipeline's patient_info object is only useful if the calculation is performed on a single patient. In the event of iteration, this object is no longer used (only the database is). The possibility of adding metadata outside the database remains an interesting option. We could consider using a json file rather than a dictionary.

On my side, things seem now to work well with the 3 iteration modes.
Please @manuegrx can you test this on your end and let me know if it works well for you now.

**Comment by manuegrx** [comment]
Thanks it is correctly working with the [regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table) using the Files_To_List brick ! 

But I have an issue with the  [input filter brick process way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) ! 

When I open the filter (for anat_file_filter for example), I can correctly select only the anat files but the input of the filter is not updated and so all the file (with the func files) are still in input for anat_file 

![image](https://github.com/user-attachments/assets/5d7f2717-555b-425b-8666-39d823853316)
![image](https://github.com/user-attachments/assets/a1ece001-770f-442f-804e-cd321c73fc9e)


I tried with an other process (just a simple smooth) and I have the same issue. I really think it was working that way before but maybe I am missing something !

**Comment by servoz** [comment]
I don't understand this sentence:
>> When I open the filter (for anat_file_filter for example), I can correctly select only the anat files but the input of the filter is not updated and so all the file (with the func files) are still in input for anat_file.

The input for these bricks will always be the database (with all its entries). It is when the pipeline is executed that the filters will be applied and the outputs created.

I've just tested again and I don't see any problems. Perhaps there's a problem with your procedure?


Can you tell exactly what's wrong (perhaps a short video of your procedure or a detailed written description of it)?

**Comment by manuegrx** [comment]
Okay I was wrong, the issue is not with the filters but I do not know why it is not working with this way (with the same data it is working using the [regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)) 

Here is a short video, if you can check that I am not missing something in my procedure ? 
[simplescreenrecorder-2024-09-18_12.34.22.zip](https://github.com/user-attachments/files/17042618/simplescreenrecorder-2024-09-18_12.34.22.zip)

**Comment by servoz** [comment]
Perhaps you would also like to iterate on the `trigger_data` and `physio_data` plugs?
![Screenshot from 2024-09-18 14-50-36](https://github.com/user-attachments/assets/3b228878-6ee3-43b1-83c8-d635cd390bfa)

**Comment by manuegrx** [comment]
Okay so I do not have the trigger and physio data for the subjects of my previous test but I tried with the data of the miadatusers project (using two time the same subject) and it is working when I iterate also on the trigger_data and physio_data. 

I suppose that when the trigger or physio data are not available we can use the  regular iterative way as it is working !

**Comment by servoz** [comment]
Normally, if the trigger and/or physiology data are not available or are corrupted, a standard regressor is used (at least, that's how it works in single-user mode).

There may be a bug if the standard regressor is not used with the iteration... To be checked and, if necessary, defined as the third issue with the CVR iteration (giving as much detail as possible to reproduce the issue, if possible the throwing of exception, etc.).

We need to ensure that the 3 iteration modes work correctly with the CVR.

I need to move on, so I'll come back to this third issue later if it exists.

I'm going to merge the populse_mia and mia_processes branches into master

**Comment by manuegrx** [comment]
I confirm that there is a third issue: 
3. when using [input filter brick process iterationway](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-input-filter-brick-process) with no physio and trigger data it is not working

The way to reproduce the error:
[simplescreenrecorder-2024-09-18_17.12.42.zip](https://github.com/user-attachments/files/17046250/simplescreenrecorder-2024-09-18_17.12.42.zip)

In my side there is no exception raised, only the warning `"Iteration_pipeline" pipeline was not successfully initialised...`

And the standard regressor is correctly used: 
```make_cvr_reg_physio_1 (mia_processes.bricks.tools.tools.Make_CVR_reg_physio) MIA node ...
Make_CVR_reg_physio brick: The generation of the individual regressor has failed!
Traceback:
  File "/home/gourieuxe/apps/sources_populse/mia_processes/mia_processes/bricks/tools/tools.py", line 3625, in list_outputs
    file_extension = self.trigger_data.lower().split(".")[-1]
AttributeError: '_Undefined' object has no attribute 'lower'
...Using the standard regressor...
Make_CVR_reg_physio brick: standard regressor generated!
```

It is working without physio and trigger files using the [regular iterative way](https://populse.github.io/populse_mia/html/documentation/pipeline_manager.html#via-a-regular-iterative-pipeline-without-use-of-the-iteration-table)

**Comment by servoz** [comment]
For my side, bugs -1, -2 and -3 now seem to have been fixed.

Please, @manuegrx , can you test on your side and if everything works fine close this ticket (it's always possible to reopen it if a new bug is discovered later!).

Note that while I was working on this ticket, I thought I noticed another bug with iteration, but it concerns populse_mia, so I'll open a ticket for populse_mia when I've managed to reproduce it. It seems that during iteration files can be ‘mixed’ (subject A's physio file with subject B's triger file, for example).

So for now, until this has been carefully checked and fixed if necessary, we need to look at the inputs generated automatically by the iteration after the calculation has been initialised to make sure everything is fine ...

**Comment by manuegrx** [comment]
Bug 3 is fixed, thank you !
